"""empty message

Revision ID: 3c8ff4f799b8
Revises: 8943f075250c
Create Date: 2026-04-13 16:18:39.933760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c8ff4f799b8'
down_revision = '8943f075250c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_text', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.String(length=300), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.create_table('comment_likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'comment_id')
    )
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follower_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('following_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.drop_constraint('followers_user_follower_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('followers_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['follower_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['following_id'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('user_follower_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthday', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('phonenumber', sa.String(length=20), nullable=False))
        batch_op.drop_column('20')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('20', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('phonenumber')
        batch_op.drop_column('birthday')

    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_follower_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('followers_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('followers_user_follower_id_fkey', 'users', ['user_follower_id'], ['id'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('following_id')
        batch_op.drop_column('follower_id')

    op.drop_table('comment_likes')
    op.drop_table('post_likes')
    op.drop_table('media')
    op.drop_table('comments')
    op.drop_table('posts')
    # ### end Alembic commands ###
